# Generated by Django 3.1.1 on 2020-09-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Links',
            },
        ),
    ]
